export const USER_VIEW_REFRESH_EVENT = "USER_VIEW_REFRESH_EVENT"
export const PRODUCT_VIEW_REFRESH_EVENT = "PRODUCT_VIEW_REFRESH_EVENT"
export const HYBRID_VIEW_REFRESH_EVENT = "HYBRID_VIEW_REFRESH_EVENT"




